/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transportonline.View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Marwah
 */
public class MenuPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form MenuPelanggan
     */
    public MenuPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMenuPel = new javax.swing.JLabel();
        jButtonTransportasi = new javax.swing.JButton();
        jButtonKurir = new javax.swing.JButton();
        jButtonRiwayatPemesanan = new javax.swing.JButton();
        jLabelPel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMenuPel.setText("Aplikasi Pemesanan Transportasi Online");

        jButtonTransportasi.setText("Transportasi");
        jButtonTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransportasiActionPerformed(evt);
            }
        });

        jButtonKurir.setText("Kurir");

        jButtonRiwayatPemesanan.setText("Riwayat Pemesanan");
        jButtonRiwayatPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRiwayatPemesananActionPerformed(evt);
            }
        });

        jLabelPel.setText("Pelanggan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabelMenuPel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRiwayatPemesanan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelPel)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelMenuPel)
                .addGap(31, 31, 31)
                .addComponent(jLabelPel)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTransportasi, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jButtonKurir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRiwayatPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransportasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTransportasiActionPerformed

    private void jButtonRiwayatPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRiwayatPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRiwayatPemesananActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonKurir() {
        return jButtonKurir;
    }

    public void setjButtonKurir(JButton jButtonKurir) {
        this.jButtonKurir = jButtonKurir;
    }

    public JButton getjButtonRiwayatPemesanan() {
        return jButtonRiwayatPemesanan;
    }

    public void setjButtonRiwayatPemesanan(JButton jButtonRiwayatPemesanan) {
        this.jButtonRiwayatPemesanan = jButtonRiwayatPemesanan;
    }

    public JButton getjButtonTransportasi() {
        return jButtonTransportasi;
    }

    public void setjButtonTransportasi(JButton jButtonTransportasi) {
        this.jButtonTransportasi = jButtonTransportasi;
    }

    public JLabel getjLabelMenuPel() {
        return jLabelMenuPel;
    }

    public void setjLabelMenuPel(JLabel jLabelMenuPel) {
        this.jLabelMenuPel = jLabelMenuPel;
    }

    public JLabel getjLabelPel() {
        return jLabelPel;
    }

    public void setjLabelPel(JLabel jLabelPel) {
        this.jLabelPel = jLabelPel;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKurir;
    private javax.swing.JButton jButtonRiwayatPemesanan;
    private javax.swing.JButton jButtonTransportasi;
    private javax.swing.JLabel jLabelMenuPel;
    private javax.swing.JLabel jLabelPel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
