/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Marwah
 */
public class Kurir extends javax.swing.JFrame {

    /**
     * Creates new form Kurir
     */
    public Kurir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelKurir = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelJk = new javax.swing.JLabel();
        jLabelNoTelp = new javax.swing.JLabel();
        jLabelLokasi = new javax.swing.JLabel();
        jLabelJenisBarang = new javax.swing.JLabel();
        jLabelTujuan = new javax.swing.JLabel();
        jLabelJarak = new javax.swing.JLabel();
        jLabelTarif = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldJk = new javax.swing.JTextField();
        jTextFieldNoTelp = new javax.swing.JTextField();
        jTextFieldLokasi = new javax.swing.JTextField();
        jTextFieldJenisBarang = new javax.swing.JTextField();
        jTextFieldTujuan = new javax.swing.JTextField();
        jTextFieldJarak = new javax.swing.JTextField();
        jTextFieldTarif = new javax.swing.JTextField();
        jButtonPesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelKurir.setText("Aplikasi Pemesanan Transportasi Online");

        jLabelNama.setText("Nama                      : ");

        jLabelJk.setText("Jenis Kelamin          :");

        jLabelNoTelp.setText("No. Telepon            :");

        jLabelLokasi.setText("Lokasi                      :");

        jLabelJenisBarang.setText("Jenis Barang           :");

        jLabelTujuan.setText("Tujuan                    :");

        jLabelJarak.setText("Jarak                      :");

        jLabelTarif.setText("Tarif                       :");

        jTextFieldJk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJkActionPerformed(evt);
            }
        });

        jButtonPesan.setText("Pesan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelLokasi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldLokasi))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelJenisBarang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldJenisBarang))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTujuan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldTujuan))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelJarak)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldJarak))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelJk)
                                        .addComponent(jLabelNama))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(jTextFieldJk)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelTarif)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jButtonPesan))
                                        .addComponent(jTextFieldTarif, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNoTelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabelKurir)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelKurir)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJk)
                    .addComponent(jTextFieldJk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoTelp)
                    .addComponent(jTextFieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLokasi)
                    .addComponent(jTextFieldLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJenisBarang)
                    .addComponent(jTextFieldJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTujuan)
                    .addComponent(jTextFieldTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJarak)
                    .addComponent(jTextFieldJarak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarif)
                    .addComponent(jTextFieldTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJkActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonPesan() {
        return jButtonPesan;
    }

    public void setjButtonPesan(JButton jButtonPesan) {
        this.jButtonPesan = jButtonPesan;
    }

    public JLabel getjLabelJarak() {
        return jLabelJarak;
    }

    public void setjLabelJarak(JLabel jLabelJarak) {
        this.jLabelJarak = jLabelJarak;
    }

    public JLabel getjLabelJenisBarang() {
        return jLabelJenisBarang;
    }

    public void setjLabelJenisBarang(JLabel jLabelJenisBarang) {
        this.jLabelJenisBarang = jLabelJenisBarang;
    }

    public JLabel getjLabelJk() {
        return jLabelJk;
    }

    public void setjLabelJk(JLabel jLabelJk) {
        this.jLabelJk = jLabelJk;
    }

    public JLabel getjLabelKurir() {
        return jLabelKurir;
    }

    public void setjLabelKurir(JLabel jLabelKurir) {
        this.jLabelKurir = jLabelKurir;
    }

    public JLabel getjLabelLokasi() {
        return jLabelLokasi;
    }

    public void setjLabelLokasi(JLabel jLabelLokasi) {
        this.jLabelLokasi = jLabelLokasi;
    }

    public JLabel getjLabelNama() {
        return jLabelNama;
    }

    public void setjLabelNama(JLabel jLabelNama) {
        this.jLabelNama = jLabelNama;
    }

    public JLabel getjLabelNoTelp() {
        return jLabelNoTelp;
    }

    public void setjLabelNoTelp(JLabel jLabelNoTelp) {
        this.jLabelNoTelp = jLabelNoTelp;
    }

    public JLabel getjLabelTarif() {
        return jLabelTarif;
    }

    public void setjLabelTarif(JLabel jLabelTarif) {
        this.jLabelTarif = jLabelTarif;
    }

    public JLabel getjLabelTujuan() {
        return jLabelTujuan;
    }

    public void setjLabelTujuan(JLabel jLabelTujuan) {
        this.jLabelTujuan = jLabelTujuan;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getjTextFieldJarak() {
        return jTextFieldJarak;
    }

    public void setjTextFieldJarak(JTextField jTextFieldJarak) {
        this.jTextFieldJarak = jTextFieldJarak;
    }

    public JTextField getjTextFieldJenisBarang() {
        return jTextFieldJenisBarang;
    }

    public void setjTextFieldJenisBarang(JTextField jTextFieldJenisBarang) {
        this.jTextFieldJenisBarang = jTextFieldJenisBarang;
    }

    public JTextField getjTextFieldJk() {
        return jTextFieldJk;
    }

    public void setjTextFieldJk(JTextField jTextFieldJk) {
        this.jTextFieldJk = jTextFieldJk;
    }

    public JTextField getjTextFieldLokasi() {
        return jTextFieldLokasi;
    }

    public void setjTextFieldLokasi(JTextField jTextFieldLokasi) {
        this.jTextFieldLokasi = jTextFieldLokasi;
    }

    public JTextField getjTextFieldNama() {
        return jTextFieldNama;
    }

    public void setjTextFieldNama(JTextField jTextFieldNama) {
        this.jTextFieldNama = jTextFieldNama;
    }

    public JTextField getjTextFieldNoTelp() {
        return jTextFieldNoTelp;
    }

    public void setjTextFieldNoTelp(JTextField jTextFieldNoTelp) {
        this.jTextFieldNoTelp = jTextFieldNoTelp;
    }

    public JTextField getjTextFieldTarif() {
        return jTextFieldTarif;
    }

    public void setjTextFieldTarif(JTextField jTextFieldTarif) {
        this.jTextFieldTarif = jTextFieldTarif;
    }

    public JTextField getjTextFieldTujuan() {
        return jTextFieldTujuan;
    }

    public void setjTextFieldTujuan(JTextField jTextFieldTujuan) {
        this.jTextFieldTujuan = jTextFieldTujuan;
    }
    
    public void AddListener(ActionListener e) {
        jButtonPesan.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesan;
    private javax.swing.JLabel jLabelJarak;
    private javax.swing.JLabel jLabelJenisBarang;
    private javax.swing.JLabel jLabelJk;
    private javax.swing.JLabel jLabelKurir;
    private javax.swing.JLabel jLabelLokasi;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNoTelp;
    private javax.swing.JLabel jLabelTarif;
    private javax.swing.JLabel jLabelTujuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldJarak;
    private javax.swing.JTextField jTextFieldJenisBarang;
    private javax.swing.JTextField jTextFieldJk;
    private javax.swing.JTextField jTextFieldLokasi;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNoTelp;
    private javax.swing.JTextField jTextFieldTarif;
    private javax.swing.JTextField jTextFieldTujuan;
    // End of variables declaration//GEN-END:variables
}
