/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Marwah
 */
public class RiwayatPemesanan extends javax.swing.JFrame {

    /**
     * Creates new form RiwayatPemesanan
     */
    public RiwayatPemesanan() {
        initComponents();
        setFrameToCenter();
    }
    
    public void setFrameToCenter() {
        Dimension scrnSize = Toolkit.getDefaultToolkit( ).getScreenSize();
        int w = getSize( ).width+700;
        int h = getSize( ).height;
        int x = ((scrnSize.width-w));
        int y = ((scrnSize.height-h+10) / 2);
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRiwayatPesanan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRiwayat = new javax.swing.JTable();
        jButtonCancelPesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRiwayatPesanan.setText("Riwayat Pemesanan");

        jScrollPane1.setViewportView(jTableRiwayat);

        jButtonCancelPesanan.setText("Cancel Pesanan");
        jButtonCancelPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRiwayatPesanan)
                .addGap(241, 241, 241))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButtonCancelPesanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRiwayatPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelPesanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelPesananActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonCancelPesanan() {
        return jButtonCancelPesanan;
    }

    public void setjButtonCancelPesanan(JButton jButtonCancelPesanan) {
        this.jButtonCancelPesanan = jButtonCancelPesanan;
    }

    public JLabel getjLabelRiwayatPesanan() {
        return jLabelRiwayatPesanan;
    }

    public void setjLabelRiwayatPesanan(JLabel jLabelRiwayatPesanan) {
        this.jLabelRiwayatPesanan = jLabelRiwayatPesanan;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTableRiwayat() {
        return jTableRiwayat;
    }

    public void setjTableRiwayat(JTable jTableRiwayat) {
        this.jTableRiwayat = jTableRiwayat;
    }
   
    public void AddListener(ActionListener e) {
        jButtonCancelPesanan.addActionListener(e);
    }
    
    public void AddMouseListener(MouseListener e){
        jTableRiwayat.addMouseListener(e);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelPesanan;
    private javax.swing.JLabel jLabelRiwayatPesanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRiwayat;
    // End of variables declaration//GEN-END:variables
}
