/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Marwah
 */
public class SignUpLogin extends javax.swing.JFrame {

    /**
     * Creates new form SignUpLogin
     */
    public SignUpLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSignUpLogin = new javax.swing.JPanel();
        jButtonSignUp = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jLabelAppsName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSignUp.setText("Sign Up");

        jButtonLogin.setText("Login");

        jLabelAppsName.setText("    Aplikasi Pemesanan Transportasi Online");

        javax.swing.GroupLayout jPanelSignUpLoginLayout = new javax.swing.GroupLayout(jPanelSignUpLogin);
        jPanelSignUpLogin.setLayout(jPanelSignUpLoginLayout);
        jPanelSignUpLoginLayout.setHorizontalGroup(
            jPanelSignUpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignUpLoginLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButtonSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanelSignUpLoginLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabelAppsName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignUpLoginLayout.setVerticalGroup(
            jPanelSignUpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpLoginLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabelAppsName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanelSignUpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSignUpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSignUpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getjButtonLogin() {
        return jButtonLogin;
    }

    public void setjButtonLogin(JButton jButtonLogin) {
        this.jButtonLogin = jButtonLogin;
    }

    public JButton getjButtonSignUp() {
        return jButtonSignUp;
    }

    public void setjButtonSignUp(JButton jButtonSignUp) {
        this.jButtonSignUp = jButtonSignUp;
    }

    public JLabel getjLabelAppsName() {
        return jLabelAppsName;
    }

    public void setjLabelAppsName(JLabel jLabelAppsName) {
        this.jLabelAppsName = jLabelAppsName;
    }

    public JPanel getjPanelSignUpLogin() {
        return jPanelSignUpLogin;
    }

    public void setjPanelSignUpLogin(JPanel jPanelSignUpLogin) {
        this.jPanelSignUpLogin = jPanelSignUpLogin;
    }
   
    public void AddListener(ActionListener e){
        jButtonLogin.addActionListener(e);
        jButtonSignUp.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSignUp;
    private javax.swing.JLabel jLabelAppsName;
    private javax.swing.JPanel jPanelSignUpLogin;
    // End of variables declaration//GEN-END:variables
}
